import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout home={true}>
      <Head>
        <title>Roy Mosby | Full-stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={utilStyles.heading2XL}>
        <h1 className={styles.title}>
          I loathe welcome messages
        </h1>


        <div className={styles.grid}>
          <Link href="/posts/images">
            <a className={styles.card}>
              <h2>Picture Page &rarr;</h2>
              <p>No need for pencils and paper, y'all.</p>
            </a>
          </Link>

          <Link href="/posts/hello-posts">
            <a className={styles.card}>
              <h2>Hello world &rarr;</h2>
              <p>Well, ain't that sumpin'.</p>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <div>
          Background customized on 
          <a
          href="https://svgbackgrounds.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          SVG Backgrounds
        </a>
        </div>
        <div>
          Illustrations from 
          <a href="https://absurd.design/">absurd.design</a>
        </div>
      </footer>
    </Layout>
  )
}
